spring:
    autoconfigure:
      exclude: org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration
    datasource:
        url: jdbc:mysql://127.0.0.1:3306/securecode
        password: fffHgy34#05123
        username: root
    jpa:
        database-platform: org.hibernate.dialect.MySQL8InnoDBDialect
        generate-ddl: true
        show-sql: true
        hibernate:
            ddl-auto: update
        properties:
            application:
                title: Welcome to Greg's Spring App
                version: 1.0
            hibernate:
                globally_quoted_identifiers: true
                dialect: org.hibernate.dialect.MySQLDialect
                format_sql: true
        open-in-view: true
    sql:
        init:
            mode: never
            continue-on-error: false

